### ISSUE TITLE
Wow - suggestions about db

### ISSUE THREAD

**Issue by jesperordrup** [n00ki/sveltekit-omakase#2]
Amazing kickoff. Ticks a lot of boxes. Haven't used drizzle orm so that's interesting (used to drizzle though)

Just to ensure getting started as easy as possible, consider default to sqlite. It's an easy way to ensure compatibility with sqlite as sometimes it's broken by using roles or default values.

👍

**Comment by n00ki** [comment]
thanks for reaching out @jesperordrup 

as mentioned in a previous related issue - I don't often use SQLite myself, so I didn't take the time to make the project compatible by default.
It seems like this could be worth exploring, though.
I'll see what I can do👍
